all: FizzBuzz TableauCarre

FizzBuzz: FizzBuzz.class TableauCarre.class
	@java FizzBuzz

FizzBuzz.class: FizzBuzz.java
	javac FizzBuzz.java

TableauCarre: TableauCarre.class
	@java TableauCarre

TableauCarre.class: TableauCarre.java
	javac TableauCarre.java

clean:
	rm -f *.class *~