######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 13 11:24:22 2014
######################################################################

TEMPLATE = app
TARGET = testMesure
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TestUnitaireMesure.h ../src/mesure.h
SOURCES += TestUnitaireMesure.cpp main.cpp ../src/mesure.cpp

LIBS += -lcppunit -ldl -lqxcppunitd
INCLUDEPATH += ../src
