CXX = g++
CXXFLAGS = -Wall

TARGET1= exo_1a
TARGET2= exo_1aa
TARGET3= exo_1b
TARGET4= exo_1c
TARGET5= exo_2

$(TARGET1): $(TARGET1).cpp
	$(CXX) -o $(TARGET1) $(TARGET1).cpp

$(TARGET2): $(TARGET2).cpp
	$(CXX) -o $(TARGET2) $(TARGET2).cpp

$(TARGET3): $(TARGET3).cpp
	$(CXX) -o $(TARGET3) $(TARGET3).cpp

$(TARGET4): $(TARGET4).cpp
	$(CXX) -o $(TARGET4) $(TARGET4).cpp

$(TARGET5): $(TARGET5).cpp
	$(CXX) -o $(TARGET5) $(TARGET5).cpp
clean:
	rm $(TARGET1) $(TARGET2) $(TARGET3) $(TARGET4) $(TARGET5)